version: 2.1

aliases:
  - &workspace ~/workspace
  - &container_config
    docker:
      - image: cimg/node:16.17.0
    working_directory: *workspace

  - &attach_workspace
    attach_workspace:
      at: *workspace

jobs:
  prepare:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Setup private npm repository
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ./.npmrc
      - run:
          name: Set engine strict
          command: echo "engine-strict=true" >> ./.npmrc
      - restore_cache:
          name: Restore node_modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm i
            fi
      - persist_to_workspace:
          root: *workspace
          paths:
            - .
      - save_cache:
          name: Save node_modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: mkdir
          command: mkdir -p dist
      - run:
          name: build
          command: npm run tsc
      - persist_to_workspace:
          root: *workspace
          paths:
            - dist
  publish:
    <<: *container_config
    working_directory: *workspace
    steps:
      - *attach_workspace
      - run:
          name: Setup private npm repository
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ./.npmrc
      - run:
          name: Keyscan Github (HACK)
          command: |
            mkdir ~/.ssh
            touch ~/.ssh/known_hosts
            chmod 0600 ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: publish
          command: npm run publish:ci

workflows:
  untagged-build:
    jobs:
      - prepare:
          context: npm-access
      - build:
          requires:
            - prepare
      - publish:
          context: npm-publishing
          requires:
            - build
          filters:
            branches:
              only:
                - master
